name: Run tests

on:
  push:
    branches:
      - master
      - 'release-*'
  pull_request:
  schedule:
      # Every day at 3:10 AM UTC
      - cron: '10 3 * * *'
  workflow_dispatch:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  extra-long-test:
    # Extra long tests
    # Only happens during the daily run, triggered by schedule
    if: github.event_name == 'schedule'
    runs-on: [Linux, RPTU, normal-memory]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: "Set up Julia"
        id: setup-julia
        uses: julia-actions/setup-julia@v2
        with:
          version: "1.10"
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1
      - name: "set test subgroup"
        run: echo "OSCAR_TEST_SUBSET=extra_long" >> $GITHUB_ENV
      - name: "Run tests"
        uses: julia-actions/julia-runtest@latest

