name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 150
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - '1.10'
        group: [ 'long' ]
        dummy: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ]
        os:
          - ubuntu-latest
        depwarn: [ '' ]

    steps:
      - uses: actions/checkout@v3
        with:
          # For Codecov, we must also fetch the parent of the HEAD commit to
          # be able to properly deal with PRs / merges
          fetch-depth: 2
      - name: "Install custom julia"
        uses: julia-actions/install-julia-from-url@main
        with:
          url: 'https://buildkite.com/organizations/julialang/pipelines/julia-release-1-dot-10/builds/200/jobs/018d53e6-d1c4-4ace-8bca-74a761cab181/artifacts/018d53f0-4fa7-4a0e-b4ed-1b34fe28166c'
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1
      - name: "limit OpenMP threads"
        if: runner.os == 'macOS'
        # restrict number of openMP threads on macOS due to oversubscription
        run: echo "OMP_NUM_THREADS=1" >> $GITHUB_ENV
      - name: "set test subgroup"
        if: ${{ matrix.group }} != ''
        run: echo "OSCAR_TEST_SUBSET=${{matrix.group}}" >> $GITHUB_ENV
      - name: "Run tests"
        uses: julia-actions/julia-runtest@latest
        with:
          annotate: ${{ matrix.julia-version == '1.10' }}
          coverage: ${{ matrix.julia-version == '1.10' }}
          depwarn: ${{ matrix.depwarn == 'depwarn=error' && 'error' || 'no' }}
      - name: "Process code coverage"
        if: matrix.julia-version == '1.10' && matrix.depwarn != 'depwarn=error'
        uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src,experimental
      - name: "Upload coverage data to Codecov"
        if: matrix.julia-version == '1.10' && matrix.depwarn != 'depwarn=error'
        continue-on-error: true
        uses: codecov/codecov-action@v3
